import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import BT3 from "@/components/BT3";
import BT4 from "@/components/BT4";
import BT5 from "@/components/BT5";
import BT7 from "@/layout/BT7";
import BT8 from "@/layout/BT8";
import BT10 from "@/layout/BT10";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://learn.rikkeiacademy.com/favicon.ico.png" />
      </Head>
     <BT3/>
     <BT4/>
     <BT5/>
     <BT7/>
     <BT8/>
     <BT10/>
 
    </>
  );
}
